# MongoDB
spring.mongodb.host=192.168.188.7
spring.mongodb.port=27017
spring.mongodb.database=riji-dev
spring.mongodb.username=root
spring.mongodb.password=a13171828306
spring.mongodb.authentication-database=admin
