# MongoDB
spring.mongodb.uri=mongodb://root:a13171828306@192.168.188.7:27017/riji-dev?authSource=admin


# Redis (Sa-Token session storage)
spring.data.redis.host=192.168.188.7
spring.data.redis.port=6380
spring.data.redis.database=0
spring.data.redis.username=
spring.data.redis.password=a13171828306
spring.data.redis.connect-timeout=3s
spring.data.redis.timeout=3s
spring.data.redis.repositories.enabled=false
