spring.application.name=riji-server

# MongoDB
spring.mongodb.uri=mongodb://100.85.53.47:27017/riji

# JWT
app.jwt.secret=riji-server-secret-key-must-be-at-least-256-bits-long-for-hs256
app.jwt.expiration=86400000
