spring.application.name=riji-server
spring.profiles.default=dev
server.port=8090

# Sa-Token
sa-token.token-name=Authorization
sa-token.token-prefix=Bearer
sa-token.timeout=86400
sa-token.is-read-header=true
sa-token.is-read-cookie=false
sa-token.is-read-body=false
sa-token.is-write-header=true

