
# MongoDB
spring.mongodb.uri=mongodb://root:a13171828306@127.0.0.1:27018/riji?authSource=admin


# Redis (Sa-Token session storage)
spring.data.redis.host=127.0.0.1
spring.data.redis.port=6390
spring.data.redis.database=0
spring.data.redis.username=
spring.data.redis.password=a13171828306
spring.data.redis.connect-timeout=3s
spring.data.redis.timeout=3s
spring.data.redis.repositories.enabled=false
